<a href="https://colab.research.google.com/github/acardell23/Linear_Algebra_Coding_projects/blob/main/Gram_Schmidt_Process_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [ ]:
# define the "messy" vectors:

r1 = [ 3, 0, 3, 0 ]
r2 = [ 3, 2, 3, 3 ]
r3 = [ -7, -4, -5, -6 ]
r4 = [ -7, -3, -11, 2 ]

# look at r1:

r1

[3, 0, 3, 0]

In [ ]:
# find the first nice basis vector u1:

# 1: pick a new vector

r1

# 2: subtract the projection of r1 onto the nice basis u1, u2, u3...
#    save this as a temporary vector n1

n1 = r1

n1

# 3: find the magnitude of n1 

np.dot(n1, n1)
np.sqrt(np.dot(n1, n1))

# 4: create the nice basis vector u1 : 1/|n1| * n1

u1 = n1 / np.sqrt(np.dot(n1,n1))
u1


array([0.70710678, 0.        , 0.70710678, 0.        ])

In [ ]:
# find the second nice basis vector u2:

# 1: pick a new vector

r2

# 2: subtract the projection of r2 onto the nice basis u1, u2, u3...
#    save this as a temporary vector n2

n2 = r2 - np.dot(r2, u1) * u1

n2

# 3: find the magnitude of n2 

np.dot(n2, n2)
np.sqrt(np.dot(n2, n2))

# 4: create the nice basis vector u2 : 1/|n2| * n2

u2 = n2 / np.sqrt(np.dot(n2,n2))
u2

array([-1.23168186e-16,  5.54700196e-01, -1.23168186e-16,  8.32050294e-01])

In [ ]:
# find the second nice basis vector u3:

# 1: pick a new vector

r3

# 2: subtract the projection of r3 onto the nice basis u1, u2, u3...
#    save this as a temporary vector n3

n3 = r3 - np.dot(r3, u1) * u1 - np.dot(r3, u2) * u2

n3

# 3: find the magnitude of n3 

np.dot(n3, n3)
np.sqrt(np.dot(n3, n3))

# 4: create the nice basis vector u3 : 1/|n3| * n3

u3 = n3 / np.sqrt(np.dot(n3,n3))
u3

array([-7.07106781e-01, -3.14018492e-16,  7.07106781e-01, -6.28036983e-16])

In [ ]:
# find the second nice basis vector u4:

# 1: pick a new vector

r4

# 2: subtract the projection of r4 onto the nice basis u1, u2, u3...
#    save this as a temporary vector n4

n4 = r4 - np.dot(r4, u1) * u1 - np.dot(r4, u2) * u2 - np.dot(r4, u3) * u3

n4

# 3: find the magnitude of n4 

np.dot(n4, n4)
np.sqrt(np.dot(n4, n4))

# 4: create the nice basis vector u4 : 1/|n4| * n4

u4 = n4 / np.sqrt(np.dot(n4,n4))
u4

array([-1.23168186e-16, -8.32050294e-01,  1.23168186e-16,  5.54700196e-01])

In [ ]:
np.dot(u1, u2)

-1.741861189847285e-16

In [ ]:
np.dot(u1, u3)

-1.0146536357569526e-17

In [ ]:
np.dot(u1, u4)

4.3370130851795835e-33

In [ ]:
np.dot(u2, u3)

-6.967444759389139e-16

In [ ]:
np.dot(u2, u4)

-1.203390859898517e-15

In [ ]:
np.dot(u3, u4)

8.709305949236507e-17

In [ ]:
np.sqrt(np.dot(u1, u1))

1.0

In [ ]:
np.sqrt(np.dot(u2, u2))

1.0

In [ ]:
np.sqrt(np.dot(u3, u3))

0.9999999999999999

In [ ]:
np.sqrt(np.dot(u4, u4))

1.0